Feature/warn user on archived GitHub repos
dxw/whippet pull request #244
Opened 2024-05-28 07:53 UTC by snim2

Warn user if they pull from an archived GitHub repo

This commit issues a warning to the user if they clone or checkout from an
archived GitHub repository. In dxw, archiving a GitHub repository containing
a dependency is likely to mean that the repository will soon be removed, and
so we need to make users aware of this. However, we do not want to cause
an error here, because we do not know whether Whippet is being run in the
context of a local development environment or as part of a deploy process.

Note that because we are only enabling this feature for a specific dxw use case,
this commit does not make the effort to abstract out GitHub-specific code in
a way that would make it easy to generalise the feature for GitLab, BitBucket,
etc. This can be done in a future PR, if anyone needs it, but ideally we would
want to improve the unit tests before hand.

## Testing

Create a `whippet.json` file with an archived repository, for example:

```json
{
  "plugins": [
     {"name": "ht-body-exporter", "src": "https://github.com/dxw/ht-body-exporter"}
  ]
}
```

and run `whippet deps update`. Check that a warning is printed.

Remove the lockfile and create a new `whippet.json` with a non-archived reposistory, e.g.:

```json
{
  "plugins": [
     {"name": "dxw-members-only", "src": "https://github.com/dxw/dxw-members-only"}
  ]
}
```

and run `whippet deps update`. Check that a warning is _not_ printed.

----

- [x] Includes tests (if new features are introduced)
- [ ] Commit message includes link to the ticket/issue
- [x] Changelog updated
- [ ] PR open against [dxw's Homebrew Tap](https://github.com/dxw/homebrew-tap/) to point the Whippet formula to the new version number

2024-05-28 10:49 UTC, RobjS requested changes
@snim2 I'm not seeing the warning. It looks like it's because that API requests are going to the incorrect URLs, e.g. it looks like it's going to `https://api.github.com/repos/git@github.com:dxw/ht-body-exporter.git`

2024-05-28 10:55 UTC, snim2 commented
> @snim2 I'm not seeing the warning. It looks like it's because that API requests are going to the incorrect URLs, e.g. it looks like it's going to `https://api.github.com/repos/git@github.com:dxw/ht-body-exporter.git`

What does your JSON file look like? I have:

```json
{
  "plugins": [
     {"name": "ht-body-exporter", "src": "git@github.com:dxw/ht-body-exporter.git"}
  ]
}
```

and I get:

```shell
❯ whippet-test deps update
[Updating plugins/ht-body-exporter]
[Checking plugins/ht-body-exporter]
WARNING: GitHub repo is archived. This dependency should be replaced before the repo is removed.
HEAD is now at 3053e2e Initial commit
#############################################
#                                           #
#  WARNING: No inspections for this plugin  #
#                                           #
#############################################

```

2024-05-28 12:25 UTC, RobjS commented
This is by whippet.json:

```
{
  "src": {
    "plugins": "git@github.com:dxw-wordpress-plugins/"
  },
  "plugins": [
    { "name": "classic-editor" },
    { "name": "co-authors-plus" },
    {
        "name": "dxw-members-only",
        "src": "git@github.com:dxw/dxw-members-only.git"
    },
    { "name": "slack" },
    { "name": "notify-users-e-mail" },
    { "name": "parsedown-party" },
    {"name": "advanced-custom-fields-pro"},
    {"name": "ht-body-exporter", "src": "https://github.com/dxw/ht-body-exporter"}

  ],
  "themes": [
    {
      "name": "govpress-product-theme",
      "src": "git@github.com:dxw/govpress-product-theme.git"
    }
  ]
}
```

I used bikeshed's whippet file as an example. Whether I use the http or ssh reference for the archived repo, I get the same result. I've put in logging to confirm that the curl request is made, but it's getting 404-ed. e.g. (with my logging included)

```
[Checking plugins/ht-body-exporter]
Checking if archived...
API URL: https://api.github.com/repos/git@github.com:dxw/ht-body-exporter.git
Curl request sent
Curl response: object(stdClass)#58 (2) {
  ["message"]=>
  string(9) "Not Found"
  ["documentation_url"]=>
  string(57) "https://docs.github.com/rest/repos/repos#get-a-repository"
}
HEAD is now at 3053e2e Initial commit
#############################################
#                                           #
#  WARNING: No inspections for this plugin  #
#                                           #
#############################################
```

2024-05-28 12:48 UTC, snim2 commented
Cannot reproduce with PHP 8.2 or 8.3

2024-05-28 13:18 UTC, snim2 commented
OK, so somehow I can reproduce the error for several repos but not this one...

2024-05-30 15:55 UTC, snim2 commented
> This is working for me now, for both `ssh` and `https` repo references.
> 
> One non-blocking suggestion: do we want to format the warning along the lines of the "No inspections for this plugin" warning, so it's less easily missed?

Yes, I think that's very wise!!!

2024-05-30 16:21 UTC, snim2 commented
New look:

```plaintext
[Checking plugins/ht-body-exporter]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! WARNING: GitHub repo is archived. This dependency !!
!! should be replaced before the repo is removed.    !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEAD is now at 3053e2e Initial commit
#############################################
#                                           #
#  WARNING: No inspections for this plugin  #
#                                           #
#############################################
```

2024-05-30 16:24 UTC, snim2 commented
Squashing before merge

2024-05-30 16:26 UTC, merged